### ISSUE TITLE
Implement laravel (epic)

### ISSUE THREAD

**Issue by gogl92** [inquid/license-plate-recognizer#2]
As a user I'd like to have an admin, a store files system, a middleware in order for me to interact with the system easier.

Acceptance criteria:
- [ ] Implement a basic Laravel project
- [ ] configure a local database to store the incoming pictures information
- [ ] configure file storage to save the incoming pictures
- [ ] create endpoints to store and retrieve the images
- [ ] implement a crud to interact with the stored information and view the images easier.
